version: '3.8'

services:
  node:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    command: [ "npm", "start" ]
    networks:
      - common
    depends_on:
      - mongo
    environment:
      MONGO_URLL: "mongodb://mongo:27017/conn"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - common

networks:
  common:
