version: '3.8'

services:
  node:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    networks:
      - common
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - common

networks:
  common:
